imports:
    - { resource: url.yaml }
    - { resource: click.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\View\Validator\:
        resource: '%kernel.project_dir%/src/Application/View/Validator/'
