services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\Url\UseCases\Handlers\:
        resource: '%kernel.project_dir%/src/Application/Url/UseCases/Handlers/'

    Application\View\Url\UrlViewFactory:
        arguments:
            $publicUri: '%env(DEFAULT_URI)%'

    Application\View\Url\LinkStatsViewFactory: ~

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true

        Application\View\Url\UrlViewFactory:
            arguments:
                $publicUri: '%env(DEFAULT_URI)%'

        Application\View\Url\LinkStatsViewFactory: ~
