services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\Url\UseCases\Handlers\:
        resource: '%kernel.project_dir%/src/Application/Url/UseCases/Handlers/'
