services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Domain\Url\Repositories\UrlRepositoryInterface:
        class: Infrastructure\Persistence\Repositories\Url\UrlRepository

    Domain\Url\Commands\Handlers\:
        resource: '%kernel.project_dir%/src/Domain/Url/Commands/Handlers/'

    Domain\Url\Queries\Handlers\:
        resource: '%kernel.project_dir%/src/Domain/Url/Queries/Handlers/'

when@test:
    services:
        _defaults:
            autoconfigure: true
            autowire: true
            public: true

        Infrastructure\Persistence\Repositories\Url\UrlRepository: ~
        Infrastructure\Persistence\Repositories\Url\InMemoryUrlRepository: ~

        Domain\Url\Repositories\UrlRepositoryInterface:
            class: Infrastructure\Persistence\Repositories\Url\TestUrlRepository
            arguments:
                $urlRepository: '@Infrastructure\Persistence\Repositories\Url\UrlRepository'
                $inMemoryUrlRepository: '@Infrastructure\Persistence\Repositories\Url\InMemoryUrlRepository'
