imports:
    - { resource: message_bus.yaml }
    - { resource: data_fixture.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Infrastructure\Kernel:
        class: Infrastructure\Kernel
